// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using AI_powered_Resume_Builder.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AI_powered_Resume_Builder.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250408133528_NormalizeResumeSections")]
    partial class NormalizeResumeSections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.AiFeedbacks.AiFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Improvements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Insights")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("MissingKeywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId")
                        .IsUnique();

                    b.ToTable("AIFeedbacks");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Keywords")
                        .HasColumnType("text[]");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.PrimitiveCollection<List<string>>("TargetJobDescriptions")
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.ResumeSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Users.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Award", b =>
                {
                    b.HasBaseType("AI_powered_Resume_Builder.Domain.Resumes.Sections.ResumeSection");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IssuingOrganization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasIndex("ResumeId");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Certification", b =>
                {
                    b.HasBaseType("AI_powered_Resume_Builder.Domain.Resumes.Sections.ResumeSection");

                    b.Property<string>("CredentialId")
                        .HasColumnType("text");

                    b.Property<string>("CredentialUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuingOrganization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ResumeId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Education", b =>
                {
                    b.HasBaseType("AI_powered_Resume_Builder.Domain.Resumes.Sections.ResumeSection");

                    b.Property<string>("Achievements")
                        .HasColumnType("text");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("GPA")
                        .HasColumnType("numeric");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("ResumeId");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Experience", b =>
                {
                    b.HasBaseType("AI_powered_Resume_Builder.Domain.Resumes.Sections.ResumeSection");

                    b.Property<string>("Achievements")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Technologies")
                        .HasColumnType("text");

                    b.HasIndex("ResumeId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Language", b =>
                {
                    b.HasBaseType("AI_powered_Resume_Builder.Domain.Resumes.Sections.ResumeSection");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("Certification")
                        .HasColumnType("text");

                    b.Property<int?>("Listening")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Reading")
                        .HasColumnType("integer");

                    b.Property<int?>("Speaking")
                        .HasColumnType("integer");

                    b.Property<int?>("Writing")
                        .HasColumnType("integer");

                    b.HasIndex("ResumeId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Project", b =>
                {
                    b.HasBaseType("AI_powered_Resume_Builder.Domain.Resumes.Sections.ResumeSection");

                    b.Property<string>("Achievements")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOngoing")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Technologies")
                        .HasColumnType("text");

                    b.HasIndex("ResumeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Publication", b =>
                {
                    b.HasBaseType("AI_powered_Resume_Builder.Domain.Resumes.Sections.ResumeSection");

                    b.Property<string>("Authors")
                        .HasColumnType("text");

                    b.Property<string>("Citation")
                        .HasColumnType("text");

                    b.Property<string>("DOI")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Impact")
                        .HasColumnType("text");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.HasIndex("ResumeId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Reference", b =>
                {
                    b.HasBaseType("AI_powered_Resume_Builder.Domain.Resumes.Sections.ResumeSection");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Relationship")
                        .HasColumnType("text");

                    b.HasIndex("ResumeId");

                    b.ToTable("References");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Skill", b =>
                {
                    b.HasBaseType("AI_powered_Resume_Builder.Domain.Resumes.Sections.ResumeSection");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("integer");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasIndex("ResumeId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Summary", b =>
                {
                    b.HasBaseType("AI_powered_Resume_Builder.Domain.Resumes.Sections.ResumeSection");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResumeId1")
                        .HasColumnType("uuid");

                    b.HasIndex("ResumeId")
                        .IsUnique();

                    b.HasIndex("ResumeId1");

                    b.ToTable("Summaries");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.AiFeedbacks.AiFeedback", b =>
                {
                    b.HasOne("AI_powered_Resume_Builder.Domain.Resumes.Resume", "Resume")
                        .WithOne("AiFeedback")
                        .HasForeignKey("AI_powered_Resume_Builder.Domain.AiFeedbacks.AiFeedback", "ResumeId");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Resume", b =>
                {
                    b.HasOne("AI_powered_Resume_Builder.Domain.Users.ApplicationUser", "ApplicationUser")
                        .WithMany("Resumes")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Award", b =>
                {
                    b.HasOne("AI_powered_Resume_Builder.Domain.Resumes.Resume", "Resume")
                        .WithMany("Awards")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Certification", b =>
                {
                    b.HasOne("AI_powered_Resume_Builder.Domain.Resumes.Resume", "Resume")
                        .WithMany("Certifications")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Education", b =>
                {
                    b.HasOne("AI_powered_Resume_Builder.Domain.Resumes.Resume", "Resume")
                        .WithMany("Education")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Experience", b =>
                {
                    b.HasOne("AI_powered_Resume_Builder.Domain.Resumes.Resume", "Resume")
                        .WithMany("Experiences")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Language", b =>
                {
                    b.HasOne("AI_powered_Resume_Builder.Domain.Resumes.Resume", "Resume")
                        .WithMany("Languages")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Project", b =>
                {
                    b.HasOne("AI_powered_Resume_Builder.Domain.Resumes.Resume", "Resume")
                        .WithMany("Projects")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Publication", b =>
                {
                    b.HasOne("AI_powered_Resume_Builder.Domain.Resumes.Resume", "Resume")
                        .WithMany("Publications")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Reference", b =>
                {
                    b.HasOne("AI_powered_Resume_Builder.Domain.Resumes.Resume", "Resume")
                        .WithMany("References")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Skill", b =>
                {
                    b.HasOne("AI_powered_Resume_Builder.Domain.Resumes.Resume", "Resume")
                        .WithMany("Skills")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Sections.Summary", b =>
                {
                    b.HasOne("AI_powered_Resume_Builder.Domain.Resumes.Resume", null)
                        .WithOne("Summary")
                        .HasForeignKey("AI_powered_Resume_Builder.Domain.Resumes.Sections.Summary", "ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI_powered_Resume_Builder.Domain.Resumes.Resume", "Resume")
                        .WithMany()
                        .HasForeignKey("ResumeId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Resumes.Resume", b =>
                {
                    b.Navigation("AiFeedback");

                    b.Navigation("Awards");

                    b.Navigation("Certifications");

                    b.Navigation("Education");

                    b.Navigation("Experiences");

                    b.Navigation("Languages");

                    b.Navigation("Projects");

                    b.Navigation("Publications");

                    b.Navigation("References");

                    b.Navigation("Skills");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("AI_powered_Resume_Builder.Domain.Users.ApplicationUser", b =>
                {
                    b.Navigation("Resumes");
                });
#pragma warning restore 612, 618
        }
    }
}
